/**
 * PIN
 * Personal Intelligent Network
 *
 * The version of the OpenAPI document: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationError } from './validationError';


export interface HTTPValidationError { 
    detail?: Array<ValidationError>;
}

