TIMEZONES = [{"display": "Etc/GMT+12 (Dateline Standard Time)", "value": "-12:Etc/GMT+12"},
             {"display": "Etc/GMT+11 (UTC-11)", "value": "-11:Etc/GMT+11"},
             {"display": "Pacific/Midway (UTC-11)", "value": "-11:Pacific/Midway"},
             {"display": "Pacific/Niue (UTC-11)", "value": "-11:Pacific/Niue"},
             {"display": "Pacific/Pago_Pago (UTC-11)", "value": "-11:Pacific/Pago_Pago"},
             {"display": "Etc/GMT+10 (Hawaiian Standard Time)", "value": "-10:Etc/GMT+10"},
             {"display": "Pacific/Honolulu (Hawaiian Standard Time)", "value": "-10:Pacific/Honolulu"},
             {"display": "Pacific/Johnston (Hawaiian Standard Time)", "value": "-10:Pacific/Johnston"},
             {"display": "Pacific/Rarotonga (Hawaiian Standard Time)", "value": "-10:Pacific/Rarotonga"},
             {"display": "Pacific/Tahiti (Hawaiian Standard Time)", "value": "-10:Pacific/Tahiti"},
             {"display": "America/Anchorage (Alaskan Standard Time)", "value": "-8:America/Anchorage"},
             {"display": "America/Juneau (Alaskan Standard Time)", "value": "-8:America/Juneau"},
             {"display": "America/Nome (Alaskan Standard Time)", "value": "-8:America/Nome"},
             {"display": "America/Sitka (Alaskan Standard Time)", "value": "-8:America/Sitka"},
             {"display": "America/Yakutat (Alaskan Standard Time)", "value": "-8:America/Yakutat"},
             {"display": "America/Santa_Isabel (Pacific Standard Time (Mexico))", "value": "-7:America/Santa_Isabel"},
             {"display": "America/Los_Angeles (Pacific Daylight Time)", "value": "-7:America/Los_Angeles"},
             {"display": "America/Tijuana (Pacific Daylight Time)", "value": "-7:America/Tijuana"},
             {"display": "America/Vancouver (Pacific Daylight Time)", "value": "-7:America/Vancouver"},
             {"display": "America/Los_Angeles (Pacific Standard Time)", "value": "-8:America/Los_Angeles"},
             {"display": "America/Tijuana (Pacific Standard Time)", "value": "-8:America/Tijuana"},
             {"display": "America/Vancouver (Pacific Standard Time)", "value": "-8:America/Vancouver"},
             {"display": "PST8PDT (Pacific Standard Time)", "value": "-8:PST8PDT"},
             {"display": "America/Creston (US Mountain Standard Time)", "value": "-7:America/Creston"},
             {"display": "America/Dawson (US Mountain Standard Time)", "value": "-7:America/Dawson"},
             {"display": "America/Dawson_Creek (US Mountain Standard Time)", "value": "-7:America/Dawson_Creek"},
             {"display": "America/Hermosillo (US Mountain Standard Time)", "value": "-7:America/Hermosillo"},
             {"display": "America/Phoenix (US Mountain Standard Time)", "value": "-7:America/Phoenix"},
             {"display": "America/Whitehorse (US Mountain Standard Time)", "value": "-7:America/Whitehorse"},
             {"display": "Etc/GMT+7 (US Mountain Standard Time)", "value": "-7:Etc/GMT+7"},
             {"display": "America/Chihuahua (Mountain Standard Time (Mexico))", "value": "-6:America/Chihuahua"},
             {"display": "America/Mazatlan (Mountain Standard Time (Mexico))", "value": "-6:America/Mazatlan"},
             {"display": "America/Boise (Mountain Standard Time)", "value": "-6:America/Boise"},
             {"display": "America/Cambridge_Bay (Mountain Standard Time)", "value": "-6:America/Cambridge_Bay"},
             {"display": "America/Denver (Mountain Standard Time)", "value": "-6:America/Denver"},
             {"display": "America/Edmonton (Mountain Standard Time)", "value": "-6:America/Edmonton"},
             {"display": "America/Inuvik (Mountain Standard Time)", "value": "-6:America/Inuvik"},
             {"display": "America/Ojinaga (Mountain Standard Time)", "value": "-6:America/Ojinaga"},
             {"display": "America/Yellowknife (Mountain Standard Time)", "value": "-6:America/Yellowknife"},
             {"display": "MST7MDT (Mountain Standard Time)", "value": "-6:MST7MDT"},
             {"display": "America/Belize (Central America Standard Time)", "value": "-6:America/Belize"},
             {"display": "America/Costa_Rica (Central America Standard Time)", "value": "-6:America/Costa_Rica"},
             {"display": "America/El_Salvador (Central America Standard Time)", "value": "-6:America/El_Salvador"},
             {"display": "America/Guatemala (Central America Standard Time)", "value": "-6:America/Guatemala"},
             {"display": "America/Managua (Central America Standard Time)", "value": "-6:America/Managua"},
             {"display": "America/Tegucigalpa (Central America Standard Time)", "value": "-6:America/Tegucigalpa"},
             {"display": "Etc/GMT+6 (Central America Standard Time)", "value": "-6:Etc/GMT+6"},
             {"display": "Pacific/Galapagos (Central America Standard Time)", "value": "-6:Pacific/Galapagos"},
             {"display": "America/Chicago (Central Standard Time)", "value": "-5:America/Chicago"},
             {"display": "America/Indiana/Knox (Central Standard Time)", "value": "-5:America/Indiana/Knox"},
             {"display": "America/Indiana/Tell_City (Central Standard Time)", "value": "-5:America/Indiana/Tell_City"},
             {"display": "America/Matamoros (Central Standard Time)", "value": "-5:America/Matamoros"},
             {"display": "America/Menominee (Central Standard Time)", "value": "-5:America/Menominee"},
             {"display": "America/North_Dakota/Beulah (Central Standard Time)",
              "value": "-5:America/North_Dakota/Beulah"},
             {"display": "America/North_Dakota/Center (Central Standard Time)",
              "value": "-5:America/North_Dakota/Center"},
             {"display": "America/North_Dakota/New_Salem (Central Standard Time)",
              "value": "-5:America/North_Dakota/New_Salem"},
             {"display": "America/Rainy_River (Central Standard Time)", "value": "-5:America/Rainy_River"},
             {"display": "America/Rankin_Inlet (Central Standard Time)", "value": "-5:America/Rankin_Inlet"},
             {"display": "America/Resolute (Central Standard Time)", "value": "-5:America/Resolute"},
             {"display": "America/Winnipeg (Central Standard Time)", "value": "-5:America/Winnipeg"},
             {"display": "CST6CDT (Central Standard Time)", "value": "-5:CST6CDT"},
             {"display": "America/Bahia_Banderas (Central Standard Time (Mexico))",
              "value": "-5:America/Bahia_Banderas"},
             {"display": "America/Cancun (Central Standard Time (Mexico))", "value": "-5:America/Cancun"},
             {"display": "America/Merida (Central Standard Time (Mexico))", "value": "-5:America/Merida"},
             {"display": "America/Mexico_City (Central Standard Time (Mexico))", "value": "-5:America/Mexico_City"},
             {"display": "America/Monterrey (Central Standard Time (Mexico))", "value": "-5:America/Monterrey"},
             {"display": "America/Regina (Canada Central Standard Time)", "value": "-6:America/Regina"},
             {"display": "America/Swift_Current (Canada Central Standard Time)", "value": "-6:America/Swift_Current"},
             {"display": "America/Bogota (SA Pacific Standard Time)", "value": "-5:America/Bogota"},
             {"display": "America/Cayman (SA Pacific Standard Time)", "value": "-5:America/Cayman"},
             {"display": "America/Coral_Harbour (SA Pacific Standard Time)", "value": "-5:America/Coral_Harbour"},
             {"display": "America/Eirunepe (SA Pacific Standard Time)", "value": "-5:America/Eirunepe"},
             {"display": "America/Guayaquil (SA Pacific Standard Time)", "value": "-5:America/Guayaquil"},
             {"display": "America/Jamaica (SA Pacific Standard Time)", "value": "-5:America/Jamaica"},
             {"display": "America/Lima (SA Pacific Standard Time)", "value": "-5:America/Lima"},
             {"display": "America/Panama (SA Pacific Standard Time)", "value": "-5:America/Panama"},
             {"display": "America/Rio_Branco (SA Pacific Standard Time)", "value": "-5:America/Rio_Branco"},
             {"display": "Etc/GMT+5 (SA Pacific Standard Time)", "value": "-5:Etc/GMT+5"},
             {"display": "America/Detroit (Eastern Standard Time)", "value": "-5:America/Detroit"},
             {"display": "America/Havana (Eastern Standard Time)", "value": "-5:America/Havana"},
             {"display": "America/Indiana/Petersburg (Eastern Standard Time)",
              "value": "-5:America/Indiana/Petersburg"},
             {"display": "America/Indiana/Vincennes (Eastern Standard Time)", "value": "-5:America/Indiana/Vincennes"},
             {"display": "America/Indiana/Winamac (Eastern Standard Time)", "value": "-5:America/Indiana/Winamac"},
             {"display": "America/Iqaluit (Eastern Standard Time)", "value": "-5:America/Iqaluit"},
             {"display": "America/Kentucky/Monticello (Eastern Standard Time)",
              "value": "-5:America/Kentucky/Monticello"},
             {"display": "America/Louisville (Eastern Standard Time)", "value": "-5:America/Louisville"},
             {"display": "America/Montreal (Eastern Standard Time)", "value": "-5:America/Montreal"},
             {"display": "America/Nassau (Eastern Standard Time)", "value": "-5:America/Nassau"},
             {"display": "America/New_York (Eastern Standard Time)", "value": "-5:America/New_York"},
             {"display": "America/Nipigon (Eastern Standard Time)", "value": "-5:America/Nipigon"},
             {"display": "America/Pangnirtung (Eastern Standard Time)", "value": "-5:America/Pangnirtung"},
             {"display": "America/Port-au-Prince (Eastern Standard Time)", "value": "-5:America/Port-au-Prince"},
             {"display": "America/Thunder_Bay (Eastern Standard Time)", "value": "-5:America/Thunder_Bay"},
             {"display": "America/Toronto (Eastern Standard Time)", "value": "-5:America/Toronto"},
             {"display": "America/Detroit (Eastern Daylight Time)", "value": "-4:America/Detroit"},
             {"display": "America/Havana (Eastern Daylight Time)", "value": "-4:America/Havana"},
             {"display": "America/Indiana/Petersburg (Eastern Daylight Time)",
              "value": "-4:America/Indiana/Petersburg"},
             {"display": "America/Indiana/Vincennes (Eastern Daylight Time)", "value": "-4:America/Indiana/Vincennes"},
             {"display": "America/Indiana/Winamac (Eastern Daylight Time)", "value": "-4:America/Indiana/Winamac"},
             {"display": "America/Iqaluit (Eastern Daylight Time)", "value": "-4:America/Iqaluit"},
             {"display": "America/Kentucky/Monticello (Eastern Daylight Time)",
              "value": "-4:America/Kentucky/Monticello"},
             {"display": "America/Louisville (Eastern Daylight Time)", "value": "-4:America/Louisville"},
             {"display": "America/Montreal (Eastern Daylight Time)", "value": "-4:America/Montreal"},
             {"display": "America/Nassau (Eastern Daylight Time)", "value": "-4:America/Nassau"},
             {"display": "America/New_York (Eastern Daylight Time)", "value": "-4:America/New_York"},
             {"display": "America/Nipigon (Eastern Daylight Time)", "value": "-4:America/Nipigon"},
             {"display": "America/Pangnirtung (Eastern Daylight Time)", "value": "-4:America/Pangnirtung"},
             {"display": "America/Port-au-Prince (Eastern Daylight Time)", "value": "-4:America/Port-au-Prince"},
             {"display": "America/Thunder_Bay (Eastern Daylight Time)", "value": "-4:America/Thunder_Bay"},
             {"display": "America/Toronto (Eastern Daylight Time)", "value": "-4:America/Toronto"},
             {"display": "America/Indiana/Marengo (US Eastern Standard Time)", "value": "-5:America/Indiana/Marengo"},
             {"display": "America/Indiana/Vevay (US Eastern Standard Time)", "value": "-5:America/Indiana/Vevay"},
             {"display": "America/Indianapolis (US Eastern Standard Time)", "value": "-5:America/Indianapolis"},
             {"display": "America/Caracas (Venezuela Standard Time)", "value": "-4.5:America/Caracas"},
             {"display": "America/Asuncion (Paraguay Standard Time)", "value": "-4:America/Asuncion"},
             {"display": "America/Glace_Bay (Atlantic Standard Time)", "value": "-3:America/Glace_Bay"},
             {"display": "America/Goose_Bay (Atlantic Standard Time)", "value": "-3:America/Goose_Bay"},
             {"display": "America/Halifax (Atlantic Standard Time)", "value": "-3:America/Halifax"},
             {"display": "America/Moncton (Atlantic Standard Time)", "value": "-3:America/Moncton"},
             {"display": "America/Thule (Atlantic Standard Time)", "value": "-3:America/Thule"},
             {"display": "Atlantic/Bermuda (Atlantic Standard Time)", "value": "-3:Atlantic/Bermuda"},
             {"display": "America/Campo_Grande (Central Brazilian Standard Time)", "value": "-4:America/Campo_Grande"},
             {"display": "America/Cuiaba (Central Brazilian Standard Time)", "value": "-4:America/Cuiaba"},
             {"display": "America/Anguilla (SA Western Standard Time)", "value": "-4:America/Anguilla"},
             {"display": "America/Antigua (SA Western Standard Time)", "value": "-4:America/Antigua"},
             {"display": "America/Aruba (SA Western Standard Time)", "value": "-4:America/Aruba"},
             {"display": "America/Barbados (SA Western Standard Time)", "value": "-4:America/Barbados"},
             {"display": "America/Blanc-Sablon (SA Western Standard Time)", "value": "-4:America/Blanc-Sablon"},
             {"display": "America/Boa_Vista (SA Western Standard Time)", "value": "-4:America/Boa_Vista"},
             {"display": "America/Curacao (SA Western Standard Time)", "value": "-4:America/Curacao"},
             {"display": "America/Dominica (SA Western Standard Time)", "value": "-4:America/Dominica"},
             {"display": "America/Grand_Turk (SA Western Standard Time)", "value": "-4:America/Grand_Turk"},
             {"display": "America/Grenada (SA Western Standard Time)", "value": "-4:America/Grenada"},
             {"display": "America/Guadeloupe (SA Western Standard Time)", "value": "-4:America/Guadeloupe"},
             {"display": "America/Guyana (SA Western Standard Time)", "value": "-4:America/Guyana"},
             {"display": "America/Kralendijk (SA Western Standard Time)", "value": "-4:America/Kralendijk"},
             {"display": "America/La_Paz (SA Western Standard Time)", "value": "-4:America/La_Paz"},
             {"display": "America/Lower_Princes (SA Western Standard Time)", "value": "-4:America/Lower_Princes"},
             {"display": "America/Manaus (SA Western Standard Time)", "value": "-4:America/Manaus"},
             {"display": "America/Marigot (SA Western Standard Time)", "value": "-4:America/Marigot"},
             {"display": "America/Martinique (SA Western Standard Time)", "value": "-4:America/Martinique"},
             {"display": "America/Montserrat (SA Western Standard Time)", "value": "-4:America/Montserrat"},
             {"display": "America/Port_of_Spain (SA Western Standard Time)", "value": "-4:America/Port_of_Spain"},
             {"display": "America/Porto_Velho (SA Western Standard Time)", "value": "-4:America/Porto_Velho"},
             {"display": "America/Puerto_Rico (SA Western Standard Time)", "value": "-4:America/Puerto_Rico"},
             {"display": "America/Santo_Domingo (SA Western Standard Time)", "value": "-4:America/Santo_Domingo"},
             {"display": "America/St_Barthelemy (SA Western Standard Time)", "value": "-4:America/St_Barthelemy"},
             {"display": "America/St_Kitts (SA Western Standard Time)", "value": "-4:America/St_Kitts"},
             {"display": "America/St_Lucia (SA Western Standard Time)", "value": "-4:America/St_Lucia"},
             {"display": "America/St_Thomas (SA Western Standard Time)", "value": "-4:America/St_Thomas"},
             {"display": "America/St_Vincent (SA Western Standard Time)", "value": "-4:America/St_Vincent"},
             {"display": "America/Tortola (SA Western Standard Time)", "value": "-4:America/Tortola"},
             {"display": "Etc/GMT+4 (SA Western Standard Time)", "value": "-4:Etc/GMT+4"},
             {"display": "America/Santiago (Pacific SA Standard Time)", "value": "-4:America/Santiago"},
             {"display": "Antarctica/Palmer (Pacific SA Standard Time)", "value": "-4:Antarctica/Palmer"},
             {"display": "America/St_Johns (Newfoundland Standard Time)", "value": "-2.5:America/St_Johns"},
             {"display": "America/Sao_Paulo (E. South America Standard Time)", "value": "-3:America/Sao_Paulo"},
             {"display": "America/Argentina/La_Rioja (Argentina Standard Time)",
              "value": "-3:America/Argentina/La_Rioja"},
             {"display": "America/Argentina/Rio_Gallegos (Argentina Standard Time)",
              "value": "-3:America/Argentina/Rio_Gallegos"},
             {"display": "America/Argentina/Salta (Argentina Standard Time)", "value": "-3:America/Argentina/Salta"},
             {"display": "America/Argentina/San_Juan (Argentina Standard Time)",
              "value": "-3:America/Argentina/San_Juan"},
             {"display": "America/Argentina/San_Luis (Argentina Standard Time)",
              "value": "-3:America/Argentina/San_Luis"},
             {"display": "America/Argentina/Tucuman (Argentina Standard Time)",
              "value": "-3:America/Argentina/Tucuman"},
             {"display": "America/Argentina/Ushuaia (Argentina Standard Time)",
              "value": "-3:America/Argentina/Ushuaia"},
             {"display": "America/Buenos_Aires (Argentina Standard Time)", "value": "-3:America/Buenos_Aires"},
             {"display": "America/Catamarca (Argentina Standard Time)", "value": "-3:America/Catamarca"},
             {"display": "America/Cordoba (Argentina Standard Time)", "value": "-3:America/Cordoba"},
             {"display": "America/Jujuy (Argentina Standard Time)", "value": "-3:America/Jujuy"},
             {"display": "America/Mendoza (Argentina Standard Time)", "value": "-3:America/Mendoza"},
             {"display": "America/Araguaina (SA Eastern Standard Time)", "value": "-3:America/Araguaina"},
             {"display": "America/Belem (SA Eastern Standard Time)", "value": "-3:America/Belem"},
             {"display": "America/Cayenne (SA Eastern Standard Time)", "value": "-3:America/Cayenne"},
             {"display": "America/Fortaleza (SA Eastern Standard Time)", "value": "-3:America/Fortaleza"},
             {"display": "America/Maceio (SA Eastern Standard Time)", "value": "-3:America/Maceio"},
             {"display": "America/Paramaribo (SA Eastern Standard Time)", "value": "-3:America/Paramaribo"},
             {"display": "America/Recife (SA Eastern Standard Time)", "value": "-3:America/Recife"},
             {"display": "America/Santarem (SA Eastern Standard Time)", "value": "-3:America/Santarem"},
             {"display": "Antarctica/Rothera (SA Eastern Standard Time)", "value": "-3:Antarctica/Rothera"},
             {"display": "Atlantic/Stanley (SA Eastern Standard Time)", "value": "-3:Atlantic/Stanley"},
             {"display": "Etc/GMT+3 (SA Eastern Standard Time)", "value": "-3:Etc/GMT+3"},
             {"display": "America/Godthab (Greenland Standard Time)", "value": "-3:America/Godthab"},
             {"display": "America/Montevideo (Montevideo Standard Time)", "value": "-3:America/Montevideo"},
             {"display": "America/Bahia (Bahia Standard Time)", "value": "-3:America/Bahia"},
             {"display": "America/Noronha (UTC-02)", "value": "-2:America/Noronha"},
             {"display": "Atlantic/South_Georgia (UTC-02)", "value": "-2:Atlantic/South_Georgia"},
             {"display": "Etc/GMT+2 (UTC-02)", "value": "-2:Etc/GMT+2"},
             {"display": "America/Scoresbysund (Azores Standard Time)", "value": "+0:America/Scoresbysund"},
             {"display": "Atlantic/Azores (Azores Standard Time)", "value": "+0:Atlantic/Azores"},
             {"display": "Atlantic/Cape_Verde (Cape Verde Standard Time)", "value": "-1:Atlantic/Cape_Verde"},
             {"display": "Etc/GMT+1 (Cape Verde Standard Time)", "value": "-1:Etc/GMT+1"},
             {"display": "Africa/Casablanca (Morocco Standard Time)", "value": "+1:Africa/Casablanca"},
             {"display": "Africa/El_Aaiun (Morocco Standard Time)", "value": "+1:Africa/El_Aaiun"},
             {"display": "America/Danmarkshavn (UTC)", "value": "+0:America/Danmarkshavn"},
             {"display": "Etc/GMT (UTC)", "value": "+0:Etc/GMT"},
             {"display": "Europe/Isle_of_Man (GMT Standard Time)", "value": "+0:Europe/Isle_of_Man"},
             {"display": "Europe/Guernsey (GMT Standard Time)", "value": "+0:Europe/Guernsey"},
             {"display": "Europe/Jersey (GMT Standard Time)", "value": "+0:Europe/Jersey"},
             {"display": "Europe/London (GMT Standard Time)", "value": "+0:Europe/London"},
             {"display": "Europe/Isle_of_Man (British Summer Time)", "value": "+1:Europe/Isle_of_Man"},
             {"display": "Europe/Guernsey (British Summer Time)", "value": "+1:Europe/Guernsey"},
             {"display": "Europe/Jersey (British Summer Time)", "value": "+1:Europe/Jersey"},
             {"display": "Europe/London (British Summer Time)", "value": "+1:Europe/London"},
             {"display": "Atlantic/Canary (GMT Standard Time)", "value": "+1:Atlantic/Canary"},
             {"display": "Atlantic/Faeroe (GMT Standard Time)", "value": "+1:Atlantic/Faeroe"},
             {"display": "Atlantic/Madeira (GMT Standard Time)", "value": "+1:Atlantic/Madeira"},
             {"display": "Europe/Dublin (GMT Standard Time)", "value": "+1:Europe/Dublin"},
             {"display": "Europe/Lisbon (GMT Standard Time)", "value": "+1:Europe/Lisbon"},
             {"display": "Africa/Abidjan (Greenwich Standard Time)", "value": "+0:Africa/Abidjan"},
             {"display": "Africa/Accra (Greenwich Standard Time)", "value": "+0:Africa/Accra"},
             {"display": "Africa/Bamako (Greenwich Standard Time)", "value": "+0:Africa/Bamako"},
             {"display": "Africa/Banjul (Greenwich Standard Time)", "value": "+0:Africa/Banjul"},
             {"display": "Africa/Bissau (Greenwich Standard Time)", "value": "+0:Africa/Bissau"},
             {"display": "Africa/Conakry (Greenwich Standard Time)", "value": "+0:Africa/Conakry"},
             {"display": "Africa/Dakar (Greenwich Standard Time)", "value": "+0:Africa/Dakar"},
             {"display": "Africa/Freetown (Greenwich Standard Time)", "value": "+0:Africa/Freetown"},
             {"display": "Africa/Lome (Greenwich Standard Time)", "value": "+0:Africa/Lome"},
             {"display": "Africa/Monrovia (Greenwich Standard Time)", "value": "+0:Africa/Monrovia"},
             {"display": "Africa/Nouakchott (Greenwich Standard Time)", "value": "+0:Africa/Nouakchott"},
             {"display": "Africa/Ouagadougou (Greenwich Standard Time)", "value": "+0:Africa/Ouagadougou"},
             {"display": "Africa/Sao_Tome (Greenwich Standard Time)", "value": "+0:Africa/Sao_Tome"},
             {"display": "Atlantic/Reykjavik (Greenwich Standard Time)", "value": "+0:Atlantic/Reykjavik"},
             {"display": "Atlantic/St_Helena (Greenwich Standard Time)", "value": "+0:Atlantic/St_Helena"},
             {"display": "Arctic/Longyearbyen (W. Europe Standard Time)", "value": "+2:Arctic/Longyearbyen"},
             {"display": "Europe/Amsterdam (W. Europe Standard Time)", "value": "+2:Europe/Amsterdam"},
             {"display": "Europe/Andorra (W. Europe Standard Time)", "value": "+2:Europe/Andorra"},
             {"display": "Europe/Berlin (W. Europe Standard Time)", "value": "+2:Europe/Berlin"},
             {"display": "Europe/Busingen (W. Europe Standard Time)", "value": "+2:Europe/Busingen"},
             {"display": "Europe/Gibraltar (W. Europe Standard Time)", "value": "+2:Europe/Gibraltar"},
             {"display": "Europe/Luxembourg (W. Europe Standard Time)", "value": "+2:Europe/Luxembourg"},
             {"display": "Europe/Malta (W. Europe Standard Time)", "value": "+2:Europe/Malta"},
             {"display": "Europe/Monaco (W. Europe Standard Time)", "value": "+2:Europe/Monaco"},
             {"display": "Europe/Oslo (W. Europe Standard Time)", "value": "+2:Europe/Oslo"},
             {"display": "Europe/Rome (W. Europe Standard Time)", "value": "+2:Europe/Rome"},
             {"display": "Europe/San_Marino (W. Europe Standard Time)", "value": "+2:Europe/San_Marino"},
             {"display": "Europe/Stockholm (W. Europe Standard Time)", "value": "+2:Europe/Stockholm"},
             {"display": "Europe/Vaduz (W. Europe Standard Time)", "value": "+2:Europe/Vaduz"},
             {"display": "Europe/Vatican (W. Europe Standard Time)", "value": "+2:Europe/Vatican"},
             {"display": "Europe/Vienna (W. Europe Standard Time)", "value": "+2:Europe/Vienna"},
             {"display": "Europe/Zurich (W. Europe Standard Time)", "value": "+2:Europe/Zurich"},
             {"display": "Europe/Belgrade (Central Europe Standard Time)", "value": "+2:Europe/Belgrade"},
             {"display": "Europe/Bratislava (Central Europe Standard Time)", "value": "+2:Europe/Bratislava"},
             {"display": "Europe/Budapest (Central Europe Standard Time)", "value": "+2:Europe/Budapest"},
             {"display": "Europe/Ljubljana (Central Europe Standard Time)", "value": "+2:Europe/Ljubljana"},
             {"display": "Europe/Podgorica (Central Europe Standard Time)", "value": "+2:Europe/Podgorica"},
             {"display": "Europe/Prague (Central Europe Standard Time)", "value": "+2:Europe/Prague"},
             {"display": "Europe/Tirane (Central Europe Standard Time)", "value": "+2:Europe/Tirane"},
             {"display": "Africa/Ceuta (Romance Standard Time)", "value": "+2:Africa/Ceuta"},
             {"display": "Europe/Brussels (Romance Standard Time)", "value": "+2:Europe/Brussels"},
             {"display": "Europe/Copenhagen (Romance Standard Time)", "value": "+2:Europe/Copenhagen"},
             {"display": "Europe/Madrid (Romance Standard Time)", "value": "+2:Europe/Madrid"},
             {"display": "Europe/Paris (Romance Standard Time)", "value": "+2:Europe/Paris"},
             {"display": "Europe/Sarajevo (Central European Standard Time)", "value": "+2:Europe/Sarajevo"},
             {"display": "Europe/Skopje (Central European Standard Time)", "value": "+2:Europe/Skopje"},
             {"display": "Europe/Warsaw (Central European Standard Time)", "value": "+2:Europe/Warsaw"},
             {"display": "Europe/Zagreb (Central European Standard Time)", "value": "+2:Europe/Zagreb"},
             {"display": "Africa/Algiers (W. Central Africa Standard Time)", "value": "+1:Africa/Algiers"},
             {"display": "Africa/Bangui (W. Central Africa Standard Time)", "value": "+1:Africa/Bangui"},
             {"display": "Africa/Brazzaville (W. Central Africa Standard Time)", "value": "+1:Africa/Brazzaville"},
             {"display": "Africa/Douala (W. Central Africa Standard Time)", "value": "+1:Africa/Douala"},
             {"display": "Africa/Kinshasa (W. Central Africa Standard Time)", "value": "+1:Africa/Kinshasa"},
             {"display": "Africa/Lagos (W. Central Africa Standard Time)", "value": "+1:Africa/Lagos"},
             {"display": "Africa/Libreville (W. Central Africa Standard Time)", "value": "+1:Africa/Libreville"},
             {"display": "Africa/Luanda (W. Central Africa Standard Time)", "value": "+1:Africa/Luanda"},
             {"display": "Africa/Malabo (W. Central Africa Standard Time)", "value": "+1:Africa/Malabo"},
             {"display": "Africa/Ndjamena (W. Central Africa Standard Time)", "value": "+1:Africa/Ndjamena"},
             {"display": "Africa/Niamey (W. Central Africa Standard Time)", "value": "+1:Africa/Niamey"},
             {"display": "Africa/Porto-Novo (W. Central Africa Standard Time)", "value": "+1:Africa/Porto-Novo"},
             {"display": "Africa/Tunis (W. Central Africa Standard Time)", "value": "+1:Africa/Tunis"},
             {"display": "Etc/GMT-1 (W. Central Africa Standard Time)", "value": "+1:Etc/GMT-1"},
             {"display": "Africa/Windhoek (Namibia Standard Time)", "value": "+1:Africa/Windhoek"},
             {"display": "Asia/Nicosia (GTB Standard Time)", "value": "+3:Asia/Nicosia"},
             {"display": "Europe/Athens (GTB Standard Time)", "value": "+3:Europe/Athens"},
             {"display": "Europe/Bucharest (GTB Standard Time)", "value": "+3:Europe/Bucharest"},
             {"display": "Europe/Chisinau (GTB Standard Time)", "value": "+3:Europe/Chisinau"},
             {"display": "Asia/Beirut (Middle East Standard Time)", "value": "+3:Asia/Beirut"},
             {"display": "Africa/Cairo (Egypt Standard Time)", "value": "+2:Africa/Cairo"},
             {"display": "Asia/Damascus (Syria Standard Time)", "value": "+3:Asia/Damascus"},
             {"display": "Asia/Nicosia (E. Europe Standard Time)", "value": "+3:Asia/Nicosia"},
             {"display": "Europe/Athens (E. Europe Standard Time)", "value": "+3:Europe/Athens"},
             {"display": "Europe/Bucharest (E. Europe Standard Time)", "value": "+3:Europe/Bucharest"},
             {"display": "Europe/Chisinau (E. Europe Standard Time)", "value": "+3:Europe/Chisinau"},
             {"display": "Europe/Helsinki (E. Europe Standard Time)", "value": "+3:Europe/Helsinki"},
             {"display": "Europe/Kiev (E. Europe Standard Time)", "value": "+3:Europe/Kiev"},
             {"display": "Europe/Mariehamn (E. Europe Standard Time)", "value": "+3:Europe/Mariehamn"},
             {"display": "Europe/Nicosia (E. Europe Standard Time)", "value": "+3:Europe/Nicosia"},
             {"display": "Europe/Riga (E. Europe Standard Time)", "value": "+3:Europe/Riga"},
             {"display": "Europe/Sofia (E. Europe Standard Time)", "value": "+3:Europe/Sofia"},
             {"display": "Europe/Tallinn (E. Europe Standard Time)", "value": "+3:Europe/Tallinn"},
             {"display": "Europe/Uzhgorod (E. Europe Standard Time)", "value": "+3:Europe/Uzhgorod"},
             {"display": "Europe/Vilnius (E. Europe Standard Time)", "value": "+3:Europe/Vilnius"},
             {"display": "Europe/Zaporozhye (E. Europe Standard Time)", "value": "+3:Europe/Zaporozhye"},
             {"display": "Africa/Blantyre (South Africa Standard Time)", "value": "+2:Africa/Blantyre"},
             {"display": "Africa/Bujumbura (South Africa Standard Time)", "value": "+2:Africa/Bujumbura"},
             {"display": "Africa/Gaborone (South Africa Standard Time)", "value": "+2:Africa/Gaborone"},
             {"display": "Africa/Harare (South Africa Standard Time)", "value": "+2:Africa/Harare"},
             {"display": "Africa/Johannesburg (South Africa Standard Time)", "value": "+2:Africa/Johannesburg"},
             {"display": "Africa/Kigali (South Africa Standard Time)", "value": "+2:Africa/Kigali"},
             {"display": "Africa/Lubumbashi (South Africa Standard Time)", "value": "+2:Africa/Lubumbashi"},
             {"display": "Africa/Lusaka (South Africa Standard Time)", "value": "+2:Africa/Lusaka"},
             {"display": "Africa/Maputo (South Africa Standard Time)", "value": "+2:Africa/Maputo"},
             {"display": "Africa/Maseru (South Africa Standard Time)", "value": "+2:Africa/Maseru"},
             {"display": "Africa/Mbabane (South Africa Standard Time)", "value": "+2:Africa/Mbabane"},
             {"display": "Etc/GMT-2 (South Africa Standard Time)", "value": "+2:Etc/GMT-2"},
             {"display": "Europe/Helsinki (FLE Standard Time)", "value": "+3:Europe/Helsinki"},
             {"display": "Europe/Kiev (FLE Standard Time)", "value": "+3:Europe/Kiev"},
             {"display": "Europe/Mariehamn (FLE Standard Time)", "value": "+3:Europe/Mariehamn"},
             {"display": "Europe/Riga (FLE Standard Time)", "value": "+3:Europe/Riga"},
             {"display": "Europe/Sofia (FLE Standard Time)", "value": "+3:Europe/Sofia"},
             {"display": "Europe/Tallinn (FLE Standard Time)", "value": "+3:Europe/Tallinn"},
             {"display": "Europe/Uzhgorod (FLE Standard Time)", "value": "+3:Europe/Uzhgorod"},
             {"display": "Europe/Vilnius (FLE Standard Time)", "value": "+3:Europe/Vilnius"},
             {"display": "Europe/Zaporozhye (FLE Standard Time)", "value": "+3:Europe/Zaporozhye"},
             {"display": "Europe/Istanbul (Turkey Standard Time)", "value": "+3:Europe/Istanbul"},
             {"display": "Asia/Jerusalem (Israel Standard Time)", "value": "+3:Asia/Jerusalem"},
             {"display": "Africa/Tripoli (Libya Standard Time)", "value": "+2:Africa/Tripoli"},
             {"display": "Asia/Amman (Jordan Standard Time)", "value": "+3:Asia/Amman"},
             {"display": "Asia/Baghdad (Arabic Standard Time)", "value": "+3:Asia/Baghdad"},
             {"display": "Europe/Kaliningrad (Kaliningrad Standard Time)", "value": "+3:Europe/Kaliningrad"},
             {"display": "Asia/Aden (Arab Standard Time)", "value": "+3:Asia/Aden"},
             {"display": "Asia/Bahrain (Arab Standard Time)", "value": "+3:Asia/Bahrain"},
             {"display": "Asia/Kuwait (Arab Standard Time)", "value": "+3:Asia/Kuwait"},
             {"display": "Asia/Qatar (Arab Standard Time)", "value": "+3:Asia/Qatar"},
             {"display": "Asia/Riyadh (Arab Standard Time)", "value": "+3:Asia/Riyadh"},
             {"display": "Africa/Addis_Ababa (E. Africa Standard Time)", "value": "+3:Africa/Addis_Ababa"},
             {"display": "Africa/Asmera (E. Africa Standard Time)", "value": "+3:Africa/Asmera"},
             {"display": "Africa/Dar_es_Salaam (E. Africa Standard Time)", "value": "+3:Africa/Dar_es_Salaam"},
             {"display": "Africa/Djibouti (E. Africa Standard Time)", "value": "+3:Africa/Djibouti"},
             {"display": "Africa/Juba (E. Africa Standard Time)", "value": "+3:Africa/Juba"},
             {"display": "Africa/Kampala (E. Africa Standard Time)", "value": "+3:Africa/Kampala"},
             {"display": "Africa/Khartoum (E. Africa Standard Time)", "value": "+3:Africa/Khartoum"},
             {"display": "Africa/Mogadishu (E. Africa Standard Time)", "value": "+3:Africa/Mogadishu"},
             {"display": "Africa/Nairobi (E. Africa Standard Time)", "value": "+3:Africa/Nairobi"},
             {"display": "Antarctica/Syowa (E. Africa Standard Time)", "value": "+3:Antarctica/Syowa"},
             {"display": "Etc/GMT-3 (E. Africa Standard Time)", "value": "+3:Etc/GMT-3"},
             {"display": "Indian/Antananarivo (E. Africa Standard Time)", "value": "+3:Indian/Antananarivo"},
             {"display": "Indian/Comoro (E. Africa Standard Time)", "value": "+3:Indian/Comoro"},
             {"display": "Indian/Mayotte (E. Africa Standard Time)", "value": "+3:Indian/Mayotte"},
             {"display": "Europe/Kirov (Moscow Standard Time)", "value": "+3:Europe/Kirov"},
             {"display": "Europe/Moscow (Moscow Standard Time)", "value": "+3:Europe/Moscow"},
             {"display": "Europe/Simferopol (Moscow Standard Time)", "value": "+3:Europe/Simferopol"},
             {"display": "Europe/Volgograd (Moscow Standard Time)", "value": "+3:Europe/Volgograd"},
             {"display": "Europe/Minsk (Moscow Standard Time)", "value": "+3:Europe/Minsk"},
             {"display": "Europe/Astrakhan (Samara Time)", "value": "+4:Europe/Astrakhan"},
             {"display": "Europe/Samara (Samara Time)", "value": "+4:Europe/Samara"},
             {"display": "Europe/Ulyanovsk (Samara Time)", "value": "+4:Europe/Ulyanovsk"},
             {"display": "Asia/Tehran (Iran Standard Time)", "value": "+4.5:Asia/Tehran"},
             {"display": "Asia/Dubai (Arabian Standard Time)", "value": "+4:Asia/Dubai"},
             {"display": "Asia/Muscat (Arabian Standard Time)", "value": "+4:Asia/Muscat"},
             {"display": "Etc/GMT-4 (Arabian Standard Time)", "value": "+4:Etc/GMT-4"},
             {"display": "Asia/Baku (Azerbaijan Standard Time)", "value": "+5:Asia/Baku"},
             {"display": "Indian/Mahe (Mauritius Standard Time)", "value": "+4:Indian/Mahe"},
             {"display": "Indian/Mauritius (Mauritius Standard Time)", "value": "+4:Indian/Mauritius"},
             {"display": "Indian/Reunion (Mauritius Standard Time)", "value": "+4:Indian/Reunion"},
             {"display": "Asia/Tbilisi (Georgian Standard Time)", "value": "+4:Asia/Tbilisi"},
             {"display": "Asia/Yerevan (Caucasus Standard Time)", "value": "+4:Asia/Yerevan"},
             {"display": "Asia/Kabul (Afghanistan Standard Time)", "value": "+4.5:Asia/Kabul"},
             {"display": "Antarctica/Mawson (West Asia Standard Time)", "value": "+5:Antarctica/Mawson"},
             {"display": "Asia/Aqtau (West Asia Standard Time)", "value": "+5:Asia/Aqtau"},
             {"display": "Asia/Aqtobe (West Asia Standard Time)", "value": "+5:Asia/Aqtobe"},
             {"display": "Asia/Ashgabat (West Asia Standard Time)", "value": "+5:Asia/Ashgabat"},
             {"display": "Asia/Dushanbe (West Asia Standard Time)", "value": "+5:Asia/Dushanbe"},
             {"display": "Asia/Oral (West Asia Standard Time)", "value": "+5:Asia/Oral"},
             {"display": "Asia/Samarkand (West Asia Standard Time)", "value": "+5:Asia/Samarkand"},
             {"display": "Asia/Tashkent (West Asia Standard Time)", "value": "+5:Asia/Tashkent"},
             {"display": "Etc/GMT-5 (West Asia Standard Time)", "value": "+5:Etc/GMT-5"},
             {"display": "Indian/Kerguelen (West Asia Standard Time)", "value": "+5:Indian/Kerguelen"},
             {"display": "Indian/Maldives (West Asia Standard Time)", "value": "+5:Indian/Maldives"},
             {"display": "Asia/Yekaterinburg (Yekaterinburg Time)", "value": "+5:Asia/Yekaterinburg"},
             {"display": "Asia/Karachi (Pakistan Standard Time)", "value": "+5:Asia/Karachi"},
             {"display": "Asia/Kolkata (India Standard Time)", "value": "+5.5:Asia/Kolkata"},
             {"display": "Asia/Calcutta (India Standard Time)", "value": "+5.5:Asia/Calcutta"},
             {"display": "Asia/Colombo (Sri Lanka Standard Time)", "value": "+5.5:Asia/Colombo"},
             {"display": "Asia/Kathmandu (Nepal Standard Time)", "value": "+5.75:Asia/Kathmandu"},
             {"display": "Antarctica/Vostok (Central Asia Standard Time)", "value": "+6:Antarctica/Vostok"},
             {"display": "Asia/Almaty (Central Asia Standard Time)", "value": "+6:Asia/Almaty"},
             {"display": "Asia/Bishkek (Central Asia Standard Time)", "value": "+6:Asia/Bishkek"},
             {"display": "Asia/Qyzylorda (Central Asia Standard Time)", "value": "+6:Asia/Qyzylorda"},
             {"display": "Asia/Urumqi (Central Asia Standard Time)", "value": "+6:Asia/Urumqi"},
             {"display": "Etc/GMT-6 (Central Asia Standard Time)", "value": "+6:Etc/GMT-6"},
             {"display": "Indian/Chagos (Central Asia Standard Time)", "value": "+6:Indian/Chagos"},
             {"display": "Asia/Dhaka (Bangladesh Standard Time)", "value": "+6:Asia/Dhaka"},
             {"display": "Asia/Thimphu (Bangladesh Standard Time)", "value": "+6:Asia/Thimphu"},
             {"display": "Asia/Rangoon (Myanmar Standard Time)", "value": "+6.5:Asia/Rangoon"},
             {"display": "Indian/Cocos (Myanmar Standard Time)", "value": "+6.5:Indian/Cocos"},
             {"display": "Antarctica/Davis (SE Asia Standard Time)", "value": "+7:Antarctica/Davis"},
             {"display": "Asia/Bangkok (SE Asia Standard Time)", "value": "+7:Asia/Bangkok"},
             {"display": "Asia/Hovd (SE Asia Standard Time)", "value": "+7:Asia/Hovd"},
             {"display": "Asia/Jakarta (SE Asia Standard Time)", "value": "+7:Asia/Jakarta"},
             {"display": "Asia/Phnom_Penh (SE Asia Standard Time)", "value": "+7:Asia/Phnom_Penh"},
             {"display": "Asia/Pontianak (SE Asia Standard Time)", "value": "+7:Asia/Pontianak"},
             {"display": "Asia/Saigon (SE Asia Standard Time)", "value": "+7:Asia/Saigon"},
             {"display": "Asia/Vientiane (SE Asia Standard Time)", "value": "+7:Asia/Vientiane"},
             {"display": "Etc/GMT-7 (SE Asia Standard Time)", "value": "+7:Etc/GMT-7"},
             {"display": "Indian/Christmas (SE Asia Standard Time)", "value": "+7:Indian/Christmas"},
             {"display": "Asia/Novokuznetsk (N. Central Asia Standard Time)", "value": "+7:Asia/Novokuznetsk"},
             {"display": "Asia/Novosibirsk (N. Central Asia Standard Time)", "value": "+7:Asia/Novosibirsk"},
             {"display": "Asia/Omsk (N. Central Asia Standard Time)", "value": "+7:Asia/Omsk"},
             {"display": "Asia/Hong_Kong (China Standard Time)", "value": "+8:Asia/Hong_Kong"},
             {"display": "Asia/Macau (China Standard Time)", "value": "+8:Asia/Macau"},
             {"display": "Asia/Shanghai (China Standard Time)", "value": "+8:Asia/Shanghai"},
             {"display": "Asia/Krasnoyarsk (North Asia Standard Time)", "value": "+8:Asia/Krasnoyarsk"},
             {"display": "Asia/Brunei (Singapore Standard Time)", "value": "+8:Asia/Brunei"},
             {"display": "Asia/Kuala_Lumpur (Singapore Standard Time)", "value": "+8:Asia/Kuala_Lumpur"},
             {"display": "Asia/Kuching (Singapore Standard Time)", "value": "+8:Asia/Kuching"},
             {"display": "Asia/Makassar (Singapore Standard Time)", "value": "+8:Asia/Makassar"},
             {"display": "Asia/Manila (Singapore Standard Time)", "value": "+8:Asia/Manila"},
             {"display": "Asia/Singapore (Singapore Standard Time)", "value": "+8:Asia/Singapore"},
             {"display": "Etc/GMT-8 (Singapore Standard Time)", "value": "+8:Etc/GMT-8"},
             {"display": "Antarctica/Casey (W. Australia Standard Time)", "value": "+8:Antarctica/Casey"},
             {"display": "Australia/Perth (W. Australia Standard Time)", "value": "+8:Australia/Perth"},
             {"display": "Asia/Taipei (Taipei Standard Time)", "value": "+8:Asia/Taipei"},
             {"display": "Asia/Choibalsan (Ulaanbaatar Standard Time)", "value": "+8:Asia/Choibalsan"},
             {"display": "Asia/Ulaanbaatar (Ulaanbaatar Standard Time)", "value": "+8:Asia/Ulaanbaatar"},
             {"display": "Asia/Irkutsk (North Asia East Standard Time)", "value": "+8:Asia/Irkutsk"},
             {"display": "Asia/Dili (Japan Standard Time)", "value": "+9:Asia/Dili"},
             {"display": "Asia/Jayapura (Japan Standard Time)", "value": "+9:Asia/Jayapura"},
             {"display": "Asia/Tokyo (Japan Standard Time)", "value": "+9:Asia/Tokyo"},
             {"display": "Etc/GMT-9 (Japan Standard Time)", "value": "+9:Etc/GMT-9"},
             {"display": "Pacific/Palau (Japan Standard Time)", "value": "+9:Pacific/Palau"},
             {"display": "Asia/Pyongyang (Korea Standard Time)", "value": "+9:Asia/Pyongyang"},
             {"display": "Asia/Seoul (Korea Standard Time)", "value": "+9:Asia/Seoul"},
             {"display": "Australia/Adelaide (Cen. Australia Standard Time)", "value": "+9.5:Australia/Adelaide"},
             {"display": "Australia/Broken_Hill (Cen. Australia Standard Time)", "value": "+9.5:Australia/Broken_Hill"},
             {"display": "Australia/Darwin (AUS Central Standard Time)", "value": "+9.5:Australia/Darwin"},
             {"display": "Australia/Brisbane (E. Australia Standard Time)", "value": "+10:Australia/Brisbane"},
             {"display": "Australia/Lindeman (E. Australia Standard Time)", "value": "+10:Australia/Lindeman"},
             {"display": "Australia/Melbourne (AUS Eastern Standard Time)", "value": "+10:Australia/Melbourne"},
             {"display": "Australia/Sydney (AUS Eastern Standard Time)", "value": "+10:Australia/Sydney"},
             {"display": "Antarctica/DumontDUrville (West Pacific Standard Time)",
              "value": "+10:Antarctica/DumontDUrville"},
             {"display": "Etc/GMT-10 (West Pacific Standard Time)", "value": "+10:Etc/GMT-10"},
             {"display": "Pacific/Guam (West Pacific Standard Time)", "value": "+10:Pacific/Guam"},
             {"display": "Pacific/Port_Moresby (West Pacific Standard Time)", "value": "+10:Pacific/Port_Moresby"},
             {"display": "Pacific/Saipan (West Pacific Standard Time)", "value": "+10:Pacific/Saipan"},
             {"display": "Pacific/Truk (West Pacific Standard Time)", "value": "+10:Pacific/Truk"},
             {"display": "Australia/Currie (Tasmania Standard Time)", "value": "+10:Australia/Currie"},
             {"display": "Australia/Hobart (Tasmania Standard Time)", "value": "+10:Australia/Hobart"},
             {"display": "Asia/Chita (Yakutsk Standard Time)", "value": "+9:Asia/Chita"},
             {"display": "Asia/Khandyga (Yakutsk Standard Time)", "value": "+9:Asia/Khandyga"},
             {"display": "Asia/Yakutsk (Yakutsk Standard Time)", "value": "+9:Asia/Yakutsk"},
             {"display": "Antarctica/Macquarie (Central Pacific Standard Time)", "value": "+11:Antarctica/Macquarie"},
             {"display": "Etc/GMT-11 (Central Pacific Standard Time)", "value": "+11:Etc/GMT-11"},
             {"display": "Pacific/Efate (Central Pacific Standard Time)", "value": "+11:Pacific/Efate"},
             {"display": "Pacific/Guadalcanal (Central Pacific Standard Time)", "value": "+11:Pacific/Guadalcanal"},
             {"display": "Pacific/Kosrae (Central Pacific Standard Time)", "value": "+11:Pacific/Kosrae"},
             {"display": "Pacific/Noumea (Central Pacific Standard Time)", "value": "+11:Pacific/Noumea"},
             {"display": "Pacific/Ponape (Central Pacific Standard Time)", "value": "+11:Pacific/Ponape"},
             {"display": "Asia/Sakhalin (Vladivostok Standard Time)", "value": "+11:Asia/Sakhalin"},
             {"display": "Asia/Ust-Nera (Vladivostok Standard Time)", "value": "+11:Asia/Ust-Nera"},
             {"display": "Asia/Vladivostok (Vladivostok Standard Time)", "value": "+11:Asia/Vladivostok"},
             {"display": "Antarctica/McMurdo (New Zealand Standard Time)", "value": "+12:Antarctica/McMurdo"},
             {"display": "Pacific/Auckland (New Zealand Standard Time)", "value": "+12:Pacific/Auckland"},
             {"display": "Etc/GMT-12 (UTC+12)", "value": "+12:Etc/GMT-12"},
             {"display": "Pacific/Funafuti (UTC+12)", "value": "+12:Pacific/Funafuti"},
             {"display": "Pacific/Kwajalein (UTC+12)", "value": "+12:Pacific/Kwajalein"},
             {"display": "Pacific/Majuro (UTC+12)", "value": "+12:Pacific/Majuro"},
             {"display": "Pacific/Nauru (UTC+12)", "value": "+12:Pacific/Nauru"},
             {"display": "Pacific/Tarawa (UTC+12)", "value": "+12:Pacific/Tarawa"},
             {"display": "Pacific/Wake (UTC+12)", "value": "+12:Pacific/Wake"},
             {"display": "Pacific/Wallis (UTC+12)", "value": "+12:Pacific/Wallis"},
             {"display": "Pacific/Fiji (Fiji Standard Time)", "value": "+12:Pacific/Fiji"},
             {"display": "Asia/Anadyr (Magadan Standard Time)", "value": "+12:Asia/Anadyr"},
             {"display": "Asia/Kamchatka (Magadan Standard Time)", "value": "+12:Asia/Kamchatka"},
             {"display": "Asia/Magadan (Magadan Standard Time)", "value": "+12:Asia/Magadan"},
             {"display": "Asia/Srednekolymsk (Magadan Standard Time)", "value": "+12:Asia/Srednekolymsk"},
             {"display": "Asia/Kamchatka (Kamchatka Standard Time)", "value": "+13:Asia/Kamchatka"},
             {"display": "Etc/GMT-13 (Tonga Standard Time)", "value": "+13:Etc/GMT-13"},
             {"display": "Pacific/Enderbury (Tonga Standard Time)", "value": "+13:Pacific/Enderbury"},
             {"display": "Pacific/Fakaofo (Tonga Standard Time)", "value": "+13:Pacific/Fakaofo"},
             {"display": "Pacific/Tongatapu (Tonga Standard Time)", "value": "+13:Pacific/Tongatapu"},
             {"display": "Pacific/Apia (Samoa Standard Time)", "value": "+13:Pacific/Apia"}]
